### ISSUE TITLE
this.$swal.fire() function not working in v3.0.6

### ISSUE THREAD

**Issue by victorybiz** [avil13/vue-sweetalert2#105]
Could this be a bug for `this.$swal.fire()`, I learnt this has been fixed in the latest release but not working in in `v3.0.6`. It only works in `v2.1.5`. 

`[Vue warn]: Error in mounted hook: "TypeError: this.$swal.fire is not a function"`

`this.$swal.fire()` not working in `v3.0.6`
`this.$swal()` works in `v3.0.6`
`this.$swal.fire()` works in `v2.1.5`.

**Comment by avil13** [comment]
Fixed in (d3720322261)
