### ISSUE TITLE
Cannot find name 'SweetAlertOptions' after upgrading to v1.6.1

### ISSUE THREAD

**Issue by Dids** [avil13/vue-sweetalert2#40]
```
ERROR in /Users/dids/<project>/node_modules/vue-sweetalert2/src/index.d.ts
5:21 Cannot find name 'SweetAlertOptions'.
    3 |
    4 | declare interface swal {
  > 5 |     mixin(options?: SweetAlertOptions): typeof swal;
      |                     ^
    6 | }
    7 |
    8 | declare module 'vue/types/vue' {
```

**Comment by Dids** [comment]
Pushed a quick PR that fixes it.
